# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Geeklist hack4good Santiago'
tagline:          'Santiago'
description:      'Unidos globalmente hackeamos un mundo mejor'
url:              http://hack4goodsantiago.github.io
baseurl:          /

author:
  name:           'Raul Pino'
  url:            https://twitter.com/p1nox

paginate:         5

# Custom vars
